
import React, { useState } from 'react';
import { generateMarketingStrategy } from '../services/gemini';
import { Loader2, Send, Sparkles } from 'lucide-react';

const StrategyTool: React.FC = () => {
  const [businessType, setBusinessType] = useState('');
  const [goal, setGoal] = useState('');
  const [strategy, setStrategy] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!businessType || !goal) return;

    setLoading(true);
    const result = await generateMarketingStrategy(businessType, goal);
    setStrategy(result);
    setLoading(false);
  };

  return (
    <div className="w-full max-w-4xl mx-auto p-8 rounded-3xl glass-card border-blue-500/20 shadow-2xl overflow-hidden relative">
      <div className="absolute top-0 right-0 p-4 opacity-10">
        <Sparkles size={120} className="text-blue-400" />
      </div>
      
      <div className="relative z-10">
        <h3 className="text-3xl font-bold mb-2 flex items-center gap-2">
          Free AI Marketing Strategy <span className="bg-blue-600 text-[10px] px-2 py-0.5 rounded-full uppercase tracking-widest align-middle">Beta</span>
        </h3>
        <p className="text-slate-400 mb-8 max-w-xl">
          Enter your business details below to get an instant, high-level marketing roadmap generated by Sanzid's custom AI assistant.
        </p>

        <form onSubmit={handleSubmit} className="grid md:grid-cols-2 gap-6 mb-8">
          <div className="space-y-2">
            <label className="text-sm font-semibold text-slate-300">Your Business Type</label>
            <input 
              type="text" 
              placeholder="e.g. E-commerce Fashion, Local Dental Clinic"
              value={businessType}
              onChange={(e) => setBusinessType(e.target.value)}
              className="w-full bg-slate-900/50 border border-slate-700 rounded-xl px-4 py-3 focus:ring-2 focus:ring-blue-500 focus:outline-none transition-all"
              required
            />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-semibold text-slate-300">Primary Goal</label>
            <input 
              type="text" 
              placeholder="e.g. Increase sales, Lead generation"
              value={goal}
              onChange={(e) => setGoal(e.target.value)}
              className="w-full bg-slate-900/50 border border-slate-700 rounded-xl px-4 py-3 focus:ring-2 focus:ring-blue-500 focus:outline-none transition-all"
              required
            />
          </div>
          <div className="md:col-span-2">
            <button 
              type="submit"
              disabled={loading}
              className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-4 rounded-xl flex items-center justify-center gap-2 transition-all disabled:opacity-50"
            >
              {loading ? <Loader2 className="animate-spin" /> : <Send size={18} />}
              {loading ? "Analyzing..." : "Generate My Strategy"}
            </button>
          </div>
        </form>

        {strategy && (
          <div className="mt-8 p-6 bg-slate-800/50 rounded-2xl border border-blue-500/30 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="flex items-start gap-4">
              <div className="bg-blue-600/20 p-2 rounded-lg">
                <Sparkles className="text-blue-400 w-5 h-5" />
              </div>
              <div className="prose prose-invert max-w-none text-slate-200 text-sm leading-relaxed">
                {strategy.split('\n').map((line, i) => (
                  <p key={i} className="mb-2 last:mb-0">{line}</p>
                ))}
                <div className="mt-6 pt-4 border-t border-slate-700 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                  <span className="text-xs text-slate-400 italic">This strategy is for initial guidance.</span>
                  <a href="#contact" className="text-blue-400 font-bold hover:underline text-sm flex items-center gap-1">
                    Book a Full Consultation <Send size={12} />
                  </a>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default StrategyTool;
